server:
  port: 80
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8
    
    
spring: 
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
      - id: user-server1
        uri: http://localhost:8080
        predicates:
          - Path=/user/get/**
      - id: user-server2
        uri: http://localhost:8080
        predicates:
          - Path=/user/lb


eureka:
  client:
    #注册
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka


